# Generated by Django 3.2.9 on 2021-11-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='slidertranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Slider Translation'},
        ),
    ]
