# Generated by Django 3.2.5 on 2021-12-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appp', '0002_auto_20211116_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Malumotalar'},
        ),
        migrations.AlterModelOptions(
            name='abouttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Malumotalar Translation'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='linklar',
            options={'verbose_name': 'Foydali Linklar'},
        ),
        migrations.AlterModelOptions(
            name='linklartranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Foydali Linklar Translation'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'News Translation'},
        ),
        migrations.AlterModelOptions(
            name='reytinglar',
            options={'verbose_name': 'Ko`rsatgichlar'},
        ),
        migrations.AlterModelOptions(
            name='reytinglartranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Ko`rsatgichlar Translation'},
        ),
    ]
